### ISSUE TITLE
Iceberg rest catalog lost all schemas and tables after restarting docker container

### ISSUE THREAD

**Issue by tnhgiang** [apache/iceberg#12866]
### Query engine

I'm using Trino

### Question

I can't find any guidance on how to locally persist data in a REST container. After restarting the container, all of my schemas and tables are gone.

**Comment by nastra** [comment]
@tnhgiang this isn't really related to Iceberg itself. In your configuration you basically need to make sure that your storage container (I'm assuming MinIO?) is persistent across restarts

**Comment by ebyhr** [comment]
I see you are using the default catalog (in-memory SQLite). Please use PostgreSQL or something.

**Comment by tnhgiang** [comment]
Thanks @ebyhr. 

Could you please give me a docs on how to configure `iceberg-rest-fixture`? I cannot find any available docs related to this issue?

**Comment by ebyhr** [comment]
You can try this docker compose yml (please download `postgresql-42.7.5.jar` beforehand):
```yml
volumes:
  data: {}

services:
  postgresql:
    container_name: postgresql
    image: postgres:12
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 3

  minio:
    container_name: minio
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - data:/data
    command: server /data --console-address ":9001"

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - data:/data
    entrypoint: mc mb /data/bucket

  irc:
    hostname: irc
    image: apache/iceberg-rest-fixture:1.8.1
    depends_on:
      postgresql:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./postgresql-42.7.5.jar:/usr/lib/iceberg-rest/postgresql-42.7.5.jar
    ports:
      - "8181:8181"
    environment:
      CATALOG_URI: jdbc:postgresql://postgresql:5432/test
      CATALOG_JDBC_USER: test
      CATALOG_JDBC_PASSWORD: test
      AWS_REGION: us-east-1
      CATALOG_WAREHOUSE: s3://bucket/warehouse/
      CATALOG_IO__IMPL: org.apache.iceberg.aws.s3.S3FileIO
      CATALOG_S3_ENDPOINT: http://minio:9000
      CATALOG_S3_PATH__STYLE__ACCESS: true
      CATALOG_S3_ACCESS__KEY__ID: minioadmin
      CATALOG_S3_SECRET__ACCESS__KEY: minioadmin

    command: java -cp /usr/lib/iceberg-rest/*:iceberg-rest-adapter.jar org.apache.iceberg.rest.RESTCatalogServer

  trino:
    container_name: trino
    image: trinodb/trino:474
    environment:
      CATALOG_MANAGEMENT: 'dynamic'
    depends_on:
      - irc
      - minio
    ports:
      - "8080:8080"
```
