### ISSUE TITLE
Kafka Connector to use only equality deletes and not position deletes

### ISSUE THREAD

**Issue by santurini** [apache/iceberg#12914]
Following this [issue](https://github.com/trinodb/trino/issues/25584), I wanted to know if it is possible to set the kafka connector to use equality deletes instead of position deletes to avoid commit error during iceberg table optimization.

This is my current iceberg connector configuration:
```yaml
{
  "name": "sink-iceberg",
  "config": {
    "iceberg.table.db.table.id-columns": "user_id",
    "iceberg.catalog.s3.endpoint": "https://minio.mydomain.com",
    "iceberg.table.db.table.partition-by": "years(created_at)",
    "iceberg.catalog.ref": "main",
    "iceberg.catalog.catalog-impl": "org.apache.iceberg.nessie.NessieCatalog",
    "iceberg.catalog.io-impl": "org.apache.iceberg.aws.s3.S3FileIO",
    "iceberg.s3.endpoint": "https://minio.mydomain.com",
    "iceberg.catalog.uri": "http://nessie.nessie.svc.cluster.local:19120/api/v2",
    "iceberg.s3.path-style-access": "true",
    "iceberg.catalog.warehouse": "s3a://warehouse",
    "iceberg.catalog.s3.path-style-access": "true",
    "name": "sink-iceberg",
    "connector.class": "io.tabular.iceberg.connect.IcebergSinkConnector",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "transforms": "unwrap",
    "topics": "trino.db.table",
    "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
    "transforms.unwrap.delete.handling.mode": "drop",
    "transforms.unwrap.drop.tombstones": "true",
    "iceberg.tables": "db.table",
    "iceberg.tables.upsert-mode-enabled": "true",
    "iceberg.tables.auto-create-enabled": "true",
    "iceberg.tables.schema-case-insensitive": "true",
    "iceberg.tables.evolve-schema-enabled": "true",
    "iceberg.catalog": "db",
    "iceberg.control.commit.interval-ms": "900000"
  }
}
```
