### ISSUE TITLE
[AWS] AssumeRoleAwsClientFactory with Flink

### ISSUE THREAD

**Issue by tiborkiss** [apache/iceberg#2636]
We have assume role based AWS setup and I would like to try Iceberg with Flink 1.11 . Unfortunately I cannot figure out the setup in case of Flink.

In the [documentation](https://iceberg.apache.org/aws) there is a section **Cross-Account and Cross-Region Access**. That in case of Spark gives an example how to pass
```
    --conf spark.sql.catalog.my_catalog.client.factory=org.apache.iceberg.aws.AssumeRoleAwsClientFactory \
    --conf spark.sql.catalog.my_catalog.client.assume-role.arn=arn:aws:iam::123456789:role/myRoleToAssume \
    --conf spark.sql.catalog.my_catalog.client.assume-role.region=ap-northeast-1
```
I cannot figure out how to apply that for Flink.
Under flink there is a `conf/sql-client-defaults.yaml`  which has a section
```
catalogs: 
  - name: myiceberg-dev
    type: iceberg
    warehouse: s3://<mybucket>/<warehouse>
    catalog-impl: org.apache.iceberg.aws.glue.GlueCatalog
    io-impl: org.apache.iceberg.aws.s3.S3FileIO
    lock-impl: org.apache.iceberg.aws.glue.DynamoLockManager
    lock.table: myGlueLockTable
```
Unfortunately it cannot parse if I add
```
    client.factory: org.apache.iceberg.aws.AssumeRoleAwsClientFactory
    client.assume-role.arn: arn:aws:iam::1212121121212:role/rolename
    client.assume-role.region: eu-central-1
```

Fails with `software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain`

But the same config chain in `~/.aws/config` is able to see S3 bucket with `AWS_PROFILE=profilename aws s3 ls`
 
Maybe someone knows how to configure AWS + Flink + Iceberg with AssumeRoleAwsClientFactory.
